### ISSUE TITLE
HMCL 启动崩端

### ISSUE THREAD

**Issue by PlayMcBKuwu** [CubeWhy/LiquidLunar#1]
*~~感觉搞得跟个崩端提交 Issue 示例一样~~*
#  
### 登录的账户类型：第三方（[LittleSkin](https://littleskin.cn/)）
#  
### 分析可能出现的错误：
1.  第一次启动成功，但没有在「AltManager」中设置账户（因为只有 离线账户 与 微软账户），选择了 离线账户 后按下了取消，可以进入 Minecraft 标题界面，但之后没有启动成功到「AltManager」。
- 分析出可能的错误为：**账户类型错误；未设置账户。**
2.  使用的 HMCL 为 Beta 版本。
- 分析出可能的错误为：**HMCL 版本不稳定。**
3.  使用的 Windows 11 x64 语言为英语。
- 分析出可能的错误为：**系统语言不正确。**

**Comment by CubeWhy** [comment]
该报错为已知错误，那个altmanager并不是最终版本，以后会改善
感谢反馈

**Comment by CubeWhy** [comment]
而且LiquidLunar启动之后不会使用第三方登录，现在是强制登入正版，离线模式按钮仅为dev测试使用（以后可能会移除此功能）
